[project]
name = "stacks-creators"
authors = []
description = "Contracts for the Stacks Creators dApp"
telemetry = true

[contracts.creator-nft]
path = "contracts/creator-nft.clar"
depends_on = []

[contracts.marketplace]
path = "contracts/marketplace.clar"
depends_on = ["creator-nft"]
