[project]
name = "stacks-creators"
authors = ["AlphaTechini"]
description = "NFT minting and marketplace platform for creators and fans."
telemetry = false

[contracts.sip009-nft-trait]
path = "contract/sip009-nft-trait.clar"

[contracts.creator-nft]
path = "contract/creator-nft.clar"
depends_on = ["sip009-nft-trait"]

[contracts.marketplace]
path = "contract/marketplace.clar"
depends_on = ["creator-nft"]
